---
services:
  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - nest-app
    ports:
      - 8080:80
    configs:
      - source: nginx_default_conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - app-network

  nest-app:
    build:
      context: .
    container_name: nest-app
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE=${DATABASE}
      - APP_VERSION=${APP_VERSION}
    ports:
      - 3000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
      - db-network

  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432
    volumes:
      - db-data:/var/lib/postgres/data
      - ./compose-config/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 15s
      retries: 10
    networks:
      - db-network

volumes:
  db-data:

configs:
  nginx_default_conf:
    file: ./compose-config/nginx/default.conf

networks:
  app-network:
  db-network:
    internal: true
